### ISSUE TITLE
Conditional unhandled 'error' event when http.request with .lookup

### ISSUE THREAD

**Issue by Jitendra9140** [Jitendra9140/MyDocs#1]
The Bug
When using http.request with a custom DNS lookup function (.lookup), errors can occur during the connection process. The bug involves these errors not being handled correctly in certain scenarios, specifically when a network issue causes the DNS lookup to fail.
The Problem
Custom DNS Lookup: When using a custom lookup function in http.request, errors can occur if the DNS lookup returns an invalid address or if the network is unreachable.
Error Handling Delay: If an error occurs during the connection phase and the error handler is not set up in time, it might result in an unhandled error. This situation can happen because http.request defers setting up error handlers to the next tick, and if an error occurs during this deferral period, it might not be caught as expected.
Exit Code Issue: Even if an error is caught, it might not exit with the expected status code. Instead, the process might exit with a non-zero status code due to the unhandled error.

**Comment by DheerenGaud** [comment]
I would like to tackle this issue and is it open

**Comment by DheerenGaud** [comment]
I Made changes in 
Custom DNS Lookup: The customLookup function checks if the hostname is [www.google.com](http://www.google.com/) and provides a custom IP. For all other domains, it uses the default DNS lookup.
TLS Connection: The makeSecureRequest function uses net to establish a connection and then upgrades it to TLS for secure communication. It sends an HTTP request and resolves the response.
Integration: This approach allows you to incorporate secure requests via custom DNS resolution while keeping your socket.io functionality intact.

**Comment by Jitendra9140** [comment]
good its working
