### ISSUE TITLE
Return Status Misuse

### ISSUE THREAD

**Issue by Jitendra9140** [Jitendra9140/MyDocs#3]
The return block inside if (res.status(201)) is incorrect. res.status() sets the status code, but it's not a function that returns the status code immediately.

**Comment by DheerenGaud** [comment]
Return Status Misuse #3  
i know how to resolve this

**Comment by DheerenGaud** [comment]
Use res.status(201).json({...}) instead.

if (await bcrypt.compare(password, user.password)) {
  const token = jwt.sign({ email: user.email }, process.env.JWT_SECRET, {
    expiresIn: 3600,
  });
  return res.status(201).json({ status: "ok", data: token });  // Fix here
}

**Comment by Jitendra9140** [comment]
Good

**Comment by Jitendra9140** [comment]
Project Update without await
