### ISSUE TITLE
Project Update without await

### ISSUE THREAD

**Issue by Jitendra9140** [Jitendra9140/MyDocs#5]
Project.findOneAndUpdate() is using .then() but there's no await, which could cause issues when handling asynchronous code.

**Comment by DheerenGaud** [comment]
I know how to handle this

**Comment by DheerenGaud** [comment]
use await or ensure proper promise handling.

`const updatedProject = await Project.findOneAndUpdate(
  { userId: userId },
  { $pull: { notifications: { expiredAt: { $lt: Date.now() } } } },
  { new: true }
);

if (!updatedProject) {
  return res.json({
    status: "error",
    data: "No user found",
    redirect: "",
  });
}

res.json({
  status: "ok",
  data: {
    userId: updatedProject.userId,
    Fname: result.data.Fname,
    projects: updatedProject.projects,
    notifications: updatedProject.notifications,
    notifCount: updatedProject.notifCount,
  },
});
`

**Comment by Jitendra9140** [comment]
good job Dheeren
